export { default as Header } from './header'
export { default as Footer } from './footer'
export { default as AboutMe } from './homeSections/aboutMe'
export { default as Contact } from './homeSections/contact'
export { default as Projects } from './homeSections/projects'